### ISSUE TITLE
Creating a new data type

### ISSUE THREAD

**Issue by pakoito** [FineCinnamon/Katz#102]
This document is a brain dump from the stuff I've been working on lately around data types. Instances to come on a separate issue.

# Data types

Example: https://github.com/FineCinnamon/Katz/blob/master/katz/src/main/kotlin/katz/data/WriterT.kt

The file reads as follows:

## package
package katz // we want all imports together for now

## alias
typealias MyTypeKind<...> = HK_N_<MyType.F, ...> // This defines the higher kind this type belongs to. _N_ is the number of parameters in ...

typealias MyTypeF<...> = HK_N - 1_<MyType.F, ...> // A partially applied type generally used for typeclass instances 

## evaluation

Here we use extension methods parametrized on generics to add functionality to specific types. This is a cool kotlin-exclusive feature you need to familiarize with. It has the advantage of not forcing inheritance, and they're found by the compiler using a type lookup. If you try to use it on a tag type you haven't defined for, you'll get a very verbose error message to tell you the lookup failed.

fun <A, B> MyTypeKind<...>.ev(): MyType<...> = this as MyType<...> // This brings the higher kind back into the implementation using a safe unchecked cast

fun <A> MyTypeKind<A>.value(): A = this.value // For simple wrappers types like Id this helper can be added to retrieve the value

## constructor

data class MyType<...>(val ...): MyTypeKind<...>

Data class to get equals and hashCode. Some data types may require using a sealed class instead, like Either or Optional do.

Use the kind typealias for the HK tag.

## tag type

class F private constructor()

This type cannot be instanced and is used exclusively in higher kinds to enable .ev() to be inferred correctly

## companion object

The companion object's duty is to hold all the smart constructors for the variations of the type. Provide at least one that'll correspond to pure() for the monad.

#### reified constructors

One common pattern used for smart constructors is overloading the invoke operator. The operator can be inlined, which enables reified generics. With reified generics, you can call the methods used for global injection of typeclass instances. This methods are named after the typeclass, so you can use monad(), foldable(), applicable()... 

#### injection of typeclass instances

TEMPORARY HACK. ONLY AVAILABLE FOR NON-PARAMETRIZED INSTANCES:

Example: https://github.com/FineCinnamon/Katz/blob/master/katz/src/main/kotlin/katz/data/NonEmptyList.kt#L62

GlobalInstance<A: Typeclass> is a helper that takes the Typeclass defined by A and adds it to a global map. This makes it available to be found using the global injection functions like monad() or functor().

## instance methods

Generally recommended to implement map and flatMap here. Other useful methods are fold, foldr/foldl, traverse, extract, and coflatMap.

These will be used by the typeclass instances directly, and can be enhanced from the required canonical implementation.

**Comment by JorgeCastilloPrz** [comment]
Thanks for this @pakoito! I would also love to have detailed info about how we are using that partially applied type on the typealias and how we benefit from it, since I kind of don't get it completely.

**Comment by pakoito** [comment]
I'm doing a formatting consistency pass on https://github.com/FineCinnamon/Katz/pull/101 to address these issues.

WriterT.ev() specifically was on its monad file. I've seen ev() also used in other typeclass instances like Traverse, so I'm moving it to the data type file instead.

**Comment by pakoito** [comment]
I've moved it to the wiki: https://github.com/FineCinnamon/Katz/wiki/Creating-a-new-data-type
