### ISSUE TITLE
Possible Supported types

### ISSUE THREAD

**Issue by arturogutierrez** [FineCinnamon/Katz#9]
- [ ] State #14 
- [x] Eval #68 
- [x] EitherT #60  
- [x] Validated #20
- [x] Reader #33
- [x] Ior #28 
- [x] Option #3 
- [x] Try #5 
- [x] Either #7 
- [x] NonEmptyList #19 
- [x] OptionT #52

**Comment by raulraja** [comment]
We can draw inspirations from here for all the types not relying on higher kinds to get started with https://github.com/typelevel/cats/tree/master/core/src/main/scala/cats/data and http://docs.scala-lang.org/overviews/collections/concrete-immutable-collection-classes

**Comment by ffgiraldez** [comment]
we have now a Roadmap #69 , start using it
